name: Website Monitor 

on:
  workflow_dispatch:       # ручной запуск
  schedule:
    - cron: "0 * * * *"    # каждый час

permissions:
  contents: read

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run monitor script
        run: python monitor.py
